version: '3'
services:
  database:
    image: 'mongo'
    restart: always
    container_name: 'bademail-mongodb'
    environment:
      - MONGO_INITDB_DATABASE=bademail
      - MONGO_INITDB_ROOT_USERNAME=runner
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_CONTAINER_PW}
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
  mongo-express:    
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: runner
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_CONTAINER_PW}
      ME_CONFIG_MONGODB_SERVER: bademail-mongodb
      
